In [1]:
my_lst = [1,2,3,4]

In [2]:
import numpy as np

In [3]:
np.array(my_lst)

array([1, 2, 3, 4])

In [4]:
arr = np.array(my_lst)

In [5]:
arr


array([1, 2, 3, 4])

In [6]:
vvvvarr = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11,3) #np.arrange(start_pt,end_pt,step_size ) step size how much it will skip


array([0, 3, 6, 9])

In [9]:
seq1 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [13]:
arr1 = np.array(seq1)

In [14]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.zeros((2,5))#w row
s and 5 column

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [21]:
np.eye(4)#identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.random.rand(5) #1D array of random numbers

array([0.26445527, 0.32168389, 0.11144524, 0.35217359, 0.54859287])

In [27]:
np.random.rand(5,5)#2D array

array([[0.3092465 , 0.1023138 , 0.14388865, 0.59351221, 0.22441899],
       [0.07893711, 0.87338872, 0.53110295, 0.96329652, 0.37859447],
       [0.23697726, 0.22390574, 0.51917393, 0.80774375, 0.61430686],
       [0.09545922, 0.04384601, 0.31556752, 0.47992584, 0.86050607],
       [0.20817351, 0.01465592, 0.63247148, 0.96380296, 0.87025967]])

In [26]:
np.random.rand(5,5,5)

array([[[0.15408252, 0.10449961, 0.59656099, 0.64080416, 0.14308518],
        [0.11847442, 0.42878226, 0.18601329, 0.20663068, 0.72492953],
        [0.60557321, 0.25608465, 0.66803226, 0.37880316, 0.00933378],
        [0.45326566, 0.23723325, 0.42856814, 0.22439794, 0.52300587],
        [0.88388227, 0.44072802, 0.01502674, 0.24694691, 0.42684496]],

       [[0.59396156, 0.92415764, 0.27383743, 0.9402212 , 0.17000806],
        [0.40766094, 0.98656421, 0.28999041, 0.13176397, 0.74436424],
        [0.30012159, 0.1788893 , 0.34262453, 0.09832794, 0.5614024 ],
        [0.90001301, 0.51994176, 0.07950776, 0.36598778, 0.78088147],
        [0.75381027, 0.18929935, 0.1933678 , 0.96559137, 0.23736968]],

       [[0.07650156, 0.14362549, 0.3807641 , 0.95878866, 0.4819494 ],
        [0.22060187, 0.28572534, 0.11965639, 0.87354621, 0.93385747],
        [0.22803159, 0.60888106, 0.3999465 , 0.12144393, 0.26820449],
        [0.24087603, 0.31218147, 0.53719737, 0.10878249, 0.48818542],
        [0.26595

In [39]:
arr2 = np.arange(25)

In [40]:
ranarr2 = np.random.randint(0,50,10)

In [41]:
ranarr2

array([23, 38, 31, 48, 19, 26, 10, 37, 36, 13])

In [42]:
arr2.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr2.max()

48

In [44]:
ranarr2.argmax()#index location of the max value

3

In [45]:
arr2.shape

(25,)